CREATE DATABASE IF NOT EXISTS laporpakdes;

USE laporpakdes;

CREATE TABLE IF NOT EXISTS laporan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  lokasi VARCHAR(255) NOT NULL,
  isi TEXT NOT NULL,
  gambar LONGTEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);